### ISSUE TITLE
let vs const

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#1]
https://github.com/OlgaZP/js-intro-home/blob/d166fbedd69cf344d859d4360f2067d8d4f50faf/js/index.js#L39
- тут также рекомендуем использовать конст. Каждая переменная должна содержать значение(я), имеющее один сенс, а тут сначала вводимое значение, потом в след строке его квадрат. Поэтому явно конст.

**Comment by OlgaZP** [comment]
Здесь выдает ошибку, если использовать const именно по причине того, что переменная изменяется в следующей строке. Я правильно понимаю суть рекомендации - добавить еще переменную другую для хранения результата возведения в квадрат?

**Comment by pecourses** [comment]
Да.

**Comment by OlgaZP** [comment]
Учла и исправила
