### ISSUE TITLE
оптимизация

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#10]
https://github.com/OlgaZP/js-intro-home/blob/17c903acf0e63e56bbe5404592feba9a5d8a45a9/js/array-home.js#L26
- можно было i инкрементировать на 2, тогда бы без проверок обошлись

**Comment by OlgaZP** [comment]
В данном случае это практически никак не влияет на скорость, поэтому не задумывалась. Но для разнообразия исправила.

**Comment by pecourses** [comment]
Абсолютно согласна. Это больше о привычках и стереотипах, чем о конкретной задаче)
