### ISSUE TITLE
пояснение

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#12]
https://github.com/OlgaZP/js-intro-home/blob/17c903acf0e63e56bbe5404592feba9a5d8a45a9/js/array-home.js#L77
- так массив меняется, а в задании предложено вывести возведенные в степень элементы, но не изменить массив

**Comment by OlgaZP** [comment]
Не внимательно прочла. Исправила конечно, но с изменением массива интереснее и почему-то сложнее далось. )
