### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#13]
https://github.com/OlgaZP/js-intro-home/blob/ea709402791785109423bb7e41b1dab89a751341/js/users-home.js#L52
// 1.2 Получить МАССИВ ПОЛНЫХ ИМЕН лиц женского пола школьного возраста (6 - 18 лет).

**Comment by OlgaZP** [comment]
Да! Увидела после занятия и уже исправила, но еще не залила изменения)
