### ISSUE TITLE
метод

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#14]
https://github.com/OlgaZP/js-intro-home/blob/ea709402791785109423bb7e41b1dab89a751341/js/users-home.js#L57
- в принципе, можно было и find использовать, только потом проверить что он вернул и вывести есть или нет, т.к. задание формулировалось "Проверить, есть ли ..."

**Comment by OlgaZP** [comment]
Много кода с проверкой, исправила на some
