### ISSUE TITLE
использование push

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#15]
https://github.com/OlgaZP/js-intro-home/blob/1fa8608bebb70b9f71be0532df8355ff306449ea/js/classes-home.js#L10
- чтобы использовать push, нужно просмотреть последнее занятие (или прочитать) про spread оператор, а так весь массив новых элементов впихивается в 0-й элемент MyArray

**Comment by OlgaZP** [comment]
Досмотрела, исправила и все заработало! Три точки, а какой смысл!)))
