### ISSUE TITLE
Нестрогое равенство

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-intro-home#2]
https://github.com/OlgaZP/js-intro-home/blob/d166fbedd69cf344d859d4360f2067d8d4f50faf/js/index.js#L64
- рекомендуем использовать всегда строгое (не)равенство, дабы избежать потенциальных ошибок. Сегодня разраб отследил, что всё корректно привел к одному типу, а завтра он (или кто будет поддерживать проект) реализовывает новую фичу и уже забывает отследить этот момент.

**Comment by OlgaZP** [comment]
исправлено и учтено
